---
title: "Time Tracker - Clockify"
author: "Steven Cognac"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, echo=FALSE, warning=FALSE)
```

```{r}
# get libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  bbest/clockify,
  dplyr, DT, ggplot2,
  quiet = TRUE)

# CHANGE THESE VARIABLES!
api_txt <- "/Users/cognac.steven/Documents/MEDS_2021_2022/02_Fall_21/EDS211_team_sci_Best/clockify_api_key.txt"
project_name <- "aqi_science"

# use API key to authenticate
CLOCKIFY_API_KEY <- readLines(api_txt)
set_api_key(CLOCKIFY_API_KEY)

# get data
d_times <- time_entries_all()
table(d_times$project_name) # confirm project_name
d_times <- d_times %>%
  filter(
    project_name == !!project_name) %>%
  select(
    task_name, time_start, duration_hrs, 
    user_name, description) %>% 
  arrange(task_name, time_start)

# show table
# d_times %>% 
#   select(
#     user_name, time_start, duration_hrs, description) %>% 
#   arrange(user_name, time_start) %>% 
#   datatable() %>%
#   formatRound(columns=c('duration_hrs'), digits=3)
```
## aqi-science {.tabset}

### Overall
```{r}
# plot ALL
plot_burndown(
  d_times,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 37)

# table ALL
datatable(d_times)
```

### 1. Import
```{r}
task <- "Import"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 2)

datatable(d_task)
```

### 2. Tidy
```{r}
task <- "Tidy"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 5)

datatable(d_task)
```



### 3. Transform
```{r}
task <- "Transform"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 10)

datatable(d_task)
```

### 4. Visualize
```{r}
task <- "Visualize"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 5)

datatable(d_task)
```


### 5. Model
```{r}
task <- "Model"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 5)

datatable(d_task)
```



### 6. Communicate
```{r}
task <- "Communicate"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-18"), # day before
  end = as.Date("2021-11-23"), # day after
  hrs = 10)

datatable(d_task)
```